services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      - elasticsearch.hosts=http://es:9200
    volumes:
      - ./kibana/config:/usr/share/kibana/config
